version: 2
updates:
- package-ecosystem: "pip"
  directory: "/backend/"
  schedule:
    interval: "cron"
    cronjob: "41 5 * * *"
  assignees:
   - "danielhmetro"
- package-ecosystem: "docker"
  directory: "/frontend"
  schedule:
    interval: "cron"
    cronjob: "4 5 * * *"
  assignees:
   - "danielhmetro"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "44 5 * * *"
  assignees:
   - "danielhmetro"
  
